//Category of Category
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_RED = "ADD_CATEGORY_RED";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_RED = "GET_CATEGORY_RED";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_RED = "UPDATE_CATEGORY_RED";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_RED = "DELETE_CATEGORY_RED";

//Category of Blogs
export const ADD_BLOG = "ADD_BLOG";
export const ADD_BLOG_RED = "ADD_BLOG_RED";
export const GET_BLOG = "GET_BLOG";
export const GET_BLOG_RED = "GET_BLOG_RED";
export const UPDATE_BLOG = "UPDATE_BLOG";
export const UPDATE_BLOG_RED = "UPDATE_BLOG_RED";
export const DELETE_BLOG = "DELETE_BLOG";
export const DELETE_BLOG_RED = "DELETE_BLOG_RED";

//Category of Contact us
export const ADD_CONTACT = "ADD_CONTACT";
export const ADD_CONTACT_RED = "ADD_CONTACT_RED";
export const GET_CONTACT = "GET_CONTACT";
export const GET_CONTACT_RED = "GET_CONTACT_RED";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const DELETE_CONTACT_RED = "DELETE_CONTACT_RED";

//Category of Newsletter
export const ADD_NEWSLETTER = "ADD_NEWSLETTER";
export const ADD_NEWSLETTER_RED = "ADD_NEWSLETTER_RED";
export const GET_NEWSLETTER = "GET_NEWSLETTER";
export const GET_NEWSLETTER_RED = "GET_NEWSLETTER_RED";
export const DELETE_NEWSLETTER = "DELETE_NEWSLETTER";
export const DELETE_NEWSLETTER_RED = "DELETE_NEWSLETTER_RED";

//Category of Testimonial
export const ADD_TESTIMONIAL = "ADD_TESTIMONIAL";
export const ADD_TESTIMONIAL_RED = "ADD_TESTIMONIAL_RED";
export const GET_TESTIMONIAL = "GET_TESTIMONIAL";
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED";
export const UPODATE_TESTIMONIAL = "UPODATE_TESTIMONIAL";
export const UPODATE_TESTIMONIAL_RED = "UPODATE_TESTIMONIAL_RED";
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL";
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED";

//Category of Favourites
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const ADD_FAVOURITE_RED = "ADD_FAVOURITE_RED";
export const GET_FAVOURITE = "GET_FAVOURITE";
export const GET_FAVOURITE_RED = "GET_FAVOURITE_RED";

export const DELETE_FAVOURITE = "DELETE_FAVOURITE";
export const DELETE_FAVOURITE_RED = "DELETE_FAVOURITE_RED";
